version: '3.7'

services:
  irlscape-app:
    container_name: irlscape-app
    build:
      context: ./app
      dockerfile: release.Dockerfile
    environment:
      TOGGL_API_TOKEN: ${TOGGL_API_TOKEN}
    ports:
      - 3000:3000
    depends_on:
      - irlscape-redis

  irlscape-redis:
    container_name: irlscape-redis
    image: redis:6-alpine
    ports:
      - 6379:6379
      