version: '3.7'

services:
  irlscape-app:
    container_name: irlscape-app
    build:
      context: ./app
      dockerfile: debug.Dockerfile
    environment:
      TOGGL_API_TOKEN: ${TOGGL_API_TOKEN}
    # Sync local changes with container
    volumes:
      - ./app/public:/app/public
      - ./app/src:/app/src
      - ./app/.next:/app/.next
    ports:
      - 3000:3000
    depends_on:
      - irlscape-redis

  irlscape-redis:
    container_name: irlscape-redis
    build:
      context: ./redis
      dockerfile: debug.Dockerfile
    ports:
      - 6379:6379